### PR TITLE
Fix Android library loading bug

### LINKED ISSUE #247: Version 0.24.1 causes failed to load library on android
Android load library on version 0.24.1 causes exception on library load.

### Symptom
When the first method is called on Kotlin side, it will try to load .so library, but it will crash the app since the ``fallbackLibrary`` property on .kt generated file points to  ``sample_library`` instead of ``sample-library`` that was generated on version 0.23.1 or less. Old versions it respects the value set on cargo.toml/boltffi.toml for package-name

### Workaround
Simple renaming the value on .kt generated file eg:

boltffi.toml \ cargo.toml
```
[package]
name = "sample-library"
```

Current Output
```
val preferredLibrary = "sample_library_jni"
val fallbackLibrary = "sample_library"
```

Expected Output
```
val preferredLibrary = "sample-library-jni"
val fallbackLibrary = "sample-library"
```

### PR DESCRIPTION
**Pull request by ahmedre**
Fixes #247.

### CODE REVIEW

File: boltffi_bindgen/src/render/kotlin/lower.rs [hunk 1]
```diff
@@ -4989,6 +4995,64 @@ mod tests {
...
+        let contract = FfiContract {
+            package: PackageInfo {
+                name: "sample-library".to_string(),
+                version: None,
+            },
+            catalog: TypeCatalog::default(),
+            functions: vec![],
+        };
+        let module = lower_module(&contract);
+        let rendered = crate::render::kotlin::templates::KotlinEmitter::emit(&module);
```
Comment (engali94) [inline boltffi_bindgen/src/render/kotlin/lower.rs]: nit: let us move this to the top f the module

File: boltffi_bindgen/src/render/kotlin/lower.rs [hunk 2]
```diff
@@ -4989,6 +4995,64 @@ mod tests {
...
+            &abi,
+            "com.example.demo".to_string(),
+            "demo".to_string(),
+            KotlinOptions {
+                library_name: Some(naming::load_library_name("configured-library")),
+                ..KotlinOptions::default()
+            },
+        )
+        .lower();
+        let rendered = crate::render::kotlin::templates::KotlinEmitter::emit(&module);
```
Comment (engali94) [inline boltffi_bindgen/src/render/kotlin/lower.rs]: similar here

**Review by engali94 — APPROVED** [review]
